#ifndef RENDER_H
#define RENDER_H

#include "sized_types.h"
#include "window.h"

struct render;

#define RENDER_ERROR_NONE 0
#define RENDER_ERROR_MEMORY -1
#define RENDER_ERROR_FILE -2
#define RENDER_ERROR_NULL -3
#define RENDER_ERROR_VULKAN_LOAD -4
#define RENDER_ERROR_VULKAN_INSTANCE -5
#define RENDER_ERROR_VULKAN_PREINST_LOAD -6
#define RENDER_ERROR_VULKAN_INST_LOAD -7
#define RENDER_ERROR_VULKAN_PHYSICAL_DEVICE -8
#define RENDER_ERROR_VULKAN_NO_DEVICES -9
#define RENDER_ERROR_VULKAN_INSTANCE_FUNC_LOAD -10
#define RENDER_ERROR_VULKAN_DEVICE_FUNC_LOAD -11
#define RENDER_ERROR_VULKAN_SURFACE -12
#define RENDER_ERROR_VULKAN_SURFACE_CAPS_IMAGE_USAGE -13
#define RENDER_ERROR_VULKAN_QUEUE_INDICES -14
#define RENDER_ERROR_VULKAN_QUEUE_INDEX_MISMATCH -15
#define RENDER_ERROR_VULKAN_CREATE_DEVICE -16
#define RENDER_ERROR_VULKAN_SURFACE_FORMAT -17
#define RENDER_ERROR_VULKAN_FORMAT_PROPERTIES_LINEAR -18
#define RENDER_ERROR_VULKAN_FORMAT_PROPERTIES_OPTIMAL -19
#define RENDER_ERROR_VULKAN_FORMAT_PROPERTIES_BUFFER -20
#define RENDER_ERROR_VULKAN_SURFACE_CAPABILITIES -21
#define RENDER_ERROR_VULKAN_SWAPCHAIN -22
#define RENDER_ERROR_VULKAN_SHADER_MODULE -23
#define RENDER_ERROR_VULKAN_SHADER_READ -24
#define RENDER_ERROR_VULKAN_DESCRIPTOR_SET_LAYOUT -25
#define RENDER_ERROR_VULKAN_PIPELINE_LAYOUT -26
#define RENDER_ERROR_VULKAN_CREATE_PIPELINE -27
#define RENDER_ERROR_VULKAN_RENDER_PASS -28
#define RENDER_ERROR_VULKAN_SWAPCHAIN_IMAGES -29
#define RENDER_ERROR_VULKAN_IMAGE_VIEW -30
#define RENDER_ERROR_VULKAN_FRAMEBUFFER -31
#define RENDER_ERROR_VULKAN_COMMAND_POOL -32
#define RENDER_ERROR_VULKAN_COMMAND_BUFFER -33
#define RENDER_ERROR_VULKAN_BUFFER -34
#define RENDER_ERROR_VULKAN_MEMORY -35
#define RENDER_ERROR_VULKAN_MEMORY_MAP -36
#define RENDER_ERROR_VULKAN_COMMAND_BUFFER_BEGIN -37
#define RENDER_ERROR_VULKAN_COMMAND_BUFFER_END -38
#define RENDER_ERROR_VULKAN_SEMAPHORE -39
#define RENDER_ERROR_VULKAN_ACQUIRE_IMAGE -40
#define RENDER_ERROR_VULKAN_QUEUE_SUBMIT -41
#define RENDER_ERROR_VULKAN_QUEUE_PRESENT -42
#define RENDER_ERROR_VULKAN_ENUMERATE_INSTANCE_EXTENSIONS -43

/* **************************************** */
/* render_<backend>.c */
struct render *render_new(struct window *, int *);
void render_del(struct render *);
int render_configure(struct render *, uint16_t, uint16_t);
void render_update(struct render *);
/* **************************************** */

#endif
